version: '3.9'

services:
  backend:
    build: .
    container_name: maktabkhoone-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo_project:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis

  celery:
    build: .
    container_name: maktabkhoone-celery
    command: celery -A todo_project worker -l info
    volumes:
      - ./todo_project:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis
      - backend

  celery-beat:
    build: .
    container_name: maktabkhoone-celery-beat
    command: celery -A todo_project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./todo_project:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis
      - backend

  redis:
    image: redis:7-alpine
    container_name: maktabkhoone-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data: